/**
 * Auto-documentation generator for AI Dev Studio projects.
 *
 * Updates project docs (PROJECT.md, ARCHITECTURE.md, API_CONTRACT.md, CHANGELOG.md)
 * based on agent role and task completion — no extra AI token cost.
 */

import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { gitManager } from './git-manager.js';
import { getProject, getLatestPlan, listPhases, listProjectAgents } from './db.js';
import type { Project, Task, AgentConfig, Phase } from './types.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Called after a task completes. Based on agent role, updates relevant docs.
 * Non-blocking — errors are caught and logged.
 */
export async function updateDocsAfterTask(
  project: Project,
  task: Task,
  agent: AgentConfig,
  log?: (msg: string) => void,
): Promise<void> {
  if (!project.repoPath) return;
  const docsDir = join(project.repoPath, 'docs');
  if (!existsSync(docsDir)) return;

  try {
    // Always regenerate all docs on every task completion
    await generateProjectMd(project, docsDir, log).catch(() => {});
    await generateArchitectureMd(project, docsDir, log).catch(() => {});
    await generateCodingStandardsMd(project, docsDir, log).catch(() => {});
    await generateApiContractMd(project, task, docsDir, log).catch(() => {});
    await appendChangelog(project, task, agent, docsDir, log);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log?.(`[docs] Hata: ${msg.slice(0, 200)}`);
  }
}

/**
 * Regenerate ALL docs for a project regardless of agent roles.
 * Useful for retroactive docs generation after fixes.
 */
export async function regenerateAllDocs(
  project: Project,
  doneTasks: Task[],
  agents: Map<string, AgentConfig>,
  log?: (msg: string) => void,
): Promise<number> {
  if (!project.repoPath) return 0;
  const docsDir = join(project.repoPath, 'docs');
  if (!existsSync(docsDir)) return 0;

  let updated = 0;

  // 1) PROJECT.md — always regenerate from plan
  try {
    await generateProjectMd(project, docsDir, log);
    updated++;
  } catch { /* skip */ }

  // 2) ARCHITECTURE.md — always regenerate from file tree
  try {
    await generateArchitectureMd(project, docsDir, log);
    updated++;
  } catch { /* skip */ }

  // 3) CODING_STANDARDS.md — always regenerate
  try {
    await generateCodingStandardsMd(project, docsDir, log);
    updated++;
  } catch { /* skip */ }

  // 4) API_CONTRACT.md — reset to TBD then rebuild from backend tasks
  const apiPath = join(docsDir, 'API_CONTRACT.md');
  try { await writeFile(apiPath, '# API Contract\n\nTBD\n', 'utf-8'); } catch { /* skip */ }
  for (const task of doneTasks) {
    const agent = agents.get(task.assignedAgent);
    if (!agent) continue;
    const role = agent.role.toLowerCase();
    if (role.startsWith('backend')) {
      try {
        await generateApiContractMd(project, task, docsDir, log);
        updated++;
      } catch { /* skip */ }
    }
  }

  // 5) CHANGELOG — reset then rebuild from done tasks
  const clPath = join(docsDir, 'CHANGELOG.md');
  try { await writeFile(clPath, '# Changelog\n\n\nAll notable changes to this project.\n', 'utf-8'); } catch { /* skip */ }
  for (const task of doneTasks) {
    const agent = agents.get(task.assignedAgent);
    if (!agent) continue;
    try {
      await appendChangelog(project, task, agent, docsDir, log);
    } catch { /* skip */ }
  }

  return updated;
}

// ---------------------------------------------------------------------------
// PROJECT.md — AI Planner
// ---------------------------------------------------------------------------

async function generateProjectMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const plan = await getLatestPlan(project.id);
  if (!plan) return;

  const phases = await listPhases(plan.id);
  const techStack = project.techStack.length > 0 ? project.techStack.join(', ') : 'Not specified';

  const lines = [
    '# Project',
    '',
    '> Generated by AI Dev Studio Planner.',
    '',
    '## Overview',
    '',
    project.description || 'No description provided.',
    '',
    '## Tech Stack',
    '',
    techStack,
    '',
    '## Requirements',
    '',
    ...phases.flatMap((phase) =>
      phase.tasks.map((t) => `- ${t.title}${t.description ? `: ${t.description.slice(0, 120)}` : ''}`),
    ),
    '',
    '## Project Plan',
    '',
    `- **Version:** ${plan.version}`,
    `- **Phases:** ${phases.length}`,
    `- **Total Tasks:** ${phases.reduce((sum, p) => sum + p.tasks.length, 0)}`,
    '',
    ...phases.map(
      (p) =>
        `### Phase ${p.order}: ${p.name}\n${p.tasks.map((t) => `- [${t.status === 'done' ? 'x' : ' '}] ${t.title} (${t.assignedAgent})`).join('\n')}`,
    ),
    '',
  ];

  await writeFile(join(docsDir, 'PROJECT.md'), lines.join('\n'), 'utf-8');
  log?.('[docs] PROJECT.md guncellendi');
}

// ---------------------------------------------------------------------------
// ARCHITECTURE.md — Architect Agent
// ---------------------------------------------------------------------------

interface TreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: TreeNode[];
}

function renderTree(nodes: TreeNode[], prefix = ''): string[] {
  const lines: string[] = [];
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];
    const isLast = i === nodes.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    lines.push(`${prefix}${connector}${node.name}`);
    if (node.children && node.children.length > 0) {
      const childPrefix = prefix + (isLast ? '    ' : '│   ');
      lines.push(...renderTree(node.children, childPrefix));
    }
  }
  return lines;
}

async function generateArchitectureMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const techStack = project.techStack.length > 0 ? project.techStack.join(', ') : 'Not specified';

  let fileTree = '';
  try {
    const tree = await gitManager.getFileTree(project.repoPath);
    const treeLines = renderTree(tree);
    fileTree = treeLines.slice(0, 60).join('\n'); // limit to 60 lines
    if (treeLines.length > 60) fileTree += '\n... (truncated)';
  } catch {
    fileTree = 'Unable to read file tree.';
  }

  const lines = [
    '# Architecture',
    '',
    '> Generated by AI Dev Studio Architect Agent.',
    '',
    '## Tech Stack',
    '',
    techStack,
    '',
    '## Project Structure',
    '',
    '```',
    fileTree,
    '```',
    '',
    '## Components',
    '',
    'See individual source files for component documentation.',
    '',
  ];

  await writeFile(join(docsDir, 'ARCHITECTURE.md'), lines.join('\n'), 'utf-8');
  log?.('[docs] ARCHITECTURE.md guncellendi');
}

// ---------------------------------------------------------------------------
// API_CONTRACT.md — Backend Agent
// ---------------------------------------------------------------------------

async function generateApiContractMd(
  project: Project,
  task: Task,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  // Only update if task is API-related
  const apiKeywords = ['api', 'route', 'endpoint', 'rest', 'controller', 'handler'];
  const isApiTask =
    apiKeywords.some((kw) => task.title.toLowerCase().includes(kw)) ||
    apiKeywords.some((kw) => task.description.toLowerCase().includes(kw));

  if (!isApiTask) return;

  const existingPath = join(docsDir, 'API_CONTRACT.md');
  let existing = '';
  try {
    existing = await readFile(existingPath, 'utf-8');
  } catch { /* ignore */ }

  // If doc already has real content (not just TBD), append rather than overwrite
  const isTBD = existing.includes('TBD') && existing.length < 50;

  const filesCreated = task.output?.filesCreated ?? [];
  const filesModified = task.output?.filesModified ?? [];
  const allFiles = [...filesCreated, ...filesModified];
  const routeFiles = allFiles.filter(
    (f) => f.includes('route') || f.includes('controller') || f.includes('api') || f.includes('handler'),
  );

  const taskEntry = [
    '',
    `## ${task.title}`,
    '',
    `> Task ID: ${task.id}`,
    `> Completed: ${task.completedAt || new Date().toISOString()}`,
    '',
    routeFiles.length > 0
      ? `**Route files:** ${routeFiles.join(', ')}`
      : `**Related files:** ${allFiles.slice(0, 5).join(', ')}`,
    '',
    task.description.slice(0, 500),
    '',
  ].join('\n');

  if (isTBD) {
    const lines = [
      '# API Contract',
      '',
      '> Generated by AI Dev Studio Backend Agent.',
      taskEntry,
    ];
    await writeFile(existingPath, lines.join('\n'), 'utf-8');
  } else {
    await writeFile(existingPath, existing + '\n' + taskEntry, 'utf-8');
  }

  log?.('[docs] API_CONTRACT.md guncellendi');
}

// ---------------------------------------------------------------------------
// CODING_STANDARDS.md — Reviewer Agent
// ---------------------------------------------------------------------------

async function generateCodingStandardsMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const existingPath = join(docsDir, 'CODING_STANDARDS.md');
  let existing = '';
  try {
    existing = await readFile(existingPath, 'utf-8');
  } catch { /* ignore */ }

  // Only fill if still TBD
  if (!existing.includes('TBD')) return;

  const techStack = project.techStack.join(', ') || 'TypeScript';

  const lines = [
    '# Coding Standards',
    '',
    '> Generated by AI Dev Studio Reviewer Agent.',
    '',
    `## Tech Stack: ${techStack}`,
    '',
    '## Formatting',
    '',
    '- ESLint + Prettier enforced automatically after each task',
    '- Single quotes, semicolons, trailing commas',
    '- Max line width: 100 characters',
    '- 2-space indentation',
    '',
    '## Naming Conventions',
    '',
    '- **Files:** kebab-case (e.g., `user-service.ts`)',
    '- **Classes/Interfaces:** PascalCase',
    '- **Functions/Variables:** camelCase',
    '- **Constants:** UPPER_SNAKE_CASE',
    '',
    '## Best Practices',
    '',
    '- Use TypeScript strict mode',
    '- Prefer `const` over `let`',
    '- Avoid `any` — use proper types',
    '- Write unit tests for business logic',
    '- Keep functions small and focused',
    '',
  ];

  await writeFile(existingPath, lines.join('\n'), 'utf-8');
  log?.('[docs] CODING_STANDARDS.md guncellendi');
}

// ---------------------------------------------------------------------------
// CHANGELOG.md — All agents (append after each task)
// ---------------------------------------------------------------------------

async function appendChangelog(
  project: Project,
  task: Task,
  agent: AgentConfig,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const changelogPath = join(docsDir, 'CHANGELOG.md');
  let existing = '';
  try {
    existing = await readFile(changelogPath, 'utf-8');
  } catch { /* ignore */ }

  const date = new Date().toISOString().split('T')[0];
  const filesCount =
    (task.output?.filesCreated?.length ?? 0) + (task.output?.filesModified?.length ?? 0);

  const entry = `\n- **${date}** — ${task.title} (${agent.name}, ${agent.role}) — ${filesCount} files\n`;

  // Avoid duplicate entries for the same task
  if (existing.includes(task.id)) return;

  // Insert after header line
  const headerEnd = existing.indexOf('\n\n');
  if (headerEnd > -1) {
    const before = existing.slice(0, headerEnd + 2);
    const after = existing.slice(headerEnd + 2);
    await writeFile(changelogPath, before + entry + after, 'utf-8');
  } else {
    await writeFile(changelogPath, existing + entry, 'utf-8');
  }

  log?.('[docs] CHANGELOG.md guncellendi');
}

// ---------------------------------------------------------------------------
// README.md — Proje tamamlandığında otomatik oluştur
// ---------------------------------------------------------------------------

/**
 * Proje bilgilerini, plan aşamalarını ve agent takımını kullanarak
 * repo kökünde profesyonel bir README.md dosyası oluşturur.
 *
 * Template-based string interpolation kullanılır; AI SDK çağrısı yapılmaz.
 * Mevcut README.md varsa üzerine yazar (otomatik güncelleme senaryosu için).
 */
export async function generateReadme(
  projectId: string,
  log?: (msg: string) => void,
): Promise<void> {
  // Proje kaydını veritabanından al
  const project = await getProject(projectId);
  if (!project) {
    log?.('[readme] Proje bulunamadı, README oluşturma atlandı');
    return;
  }

  if (!project.repoPath) {
    log?.('[readme] repoPath tanımlı değil, README oluşturma atlandı');
    return;
  }

  try {
    // ---- Plan ve görev bilgilerini topla ----
    const plan = await getLatestPlan(projectId);
    const phases: Phase[] = plan ? await listPhases(plan.id) : [];

    const totalTasks = phases.reduce((sum, p) => sum + (p.tasks?.length ?? 0), 0);
    const doneTasks = phases.reduce(
      (sum, p) => sum + (p.tasks?.filter((t) => t.status === 'done').length ?? 0),
      0,
    );

    // ---- Agent takım bilgilerini topla ----
    const agents = await listProjectAgents(projectId);
    const agentCount = agents.length;

    // Rol → benzersiz agent isimlerini grupla (kısa takım özeti için)
    const roleMap = new Map<string, string[]>();
    for (const a of agents) {
      if (!roleMap.has(a.role)) roleMap.set(a.role, []);
      roleMap.get(a.role)!.push(a.name);
    }
    const teamLines = [...roleMap.entries()].map(
      ([role, names]) => `- **${capitalize(role)}**: ${names.join(', ')}`,
    );

    // ---- Tech Stack ----
    const techItems =
      project.techStack.length > 0
        ? project.techStack.map((t) => `- ${t}`)
        : ['- Not specified'];

    // ---- Dosya ağacını al (proje yapısı bölümü için) ----
    let fileTree = '';
    try {
      const tree = await gitManager.getFileTree(project.repoPath);
      const treeLines = renderTree(tree);
      // Yalnızca ilk 50 satırı göster — çok uzun README'lerden kaçın
      fileTree = treeLines.slice(0, 50).join('\n');
      if (treeLines.length > 50) fileTree += '\n... (devamı var)';
    } catch {
      fileTree = 'Dosya yapısı okunamadı.';
    }

    // ---- ARCHITECTURE.md'den özet al (varsa) ----
    let architectureSummary = '';
    try {
      const archPath = join(project.repoPath, 'docs', 'ARCHITECTURE.md');
      if (existsSync(archPath)) {
        const archContent = await readFile(archPath, 'utf-8');
        // İlk 30 satırı özetle kullan (başlık hariç)
        const archLines = archContent
          .split('\n')
          .filter((l) => !l.startsWith('# '))  // Ana başlığı atla
          .slice(0, 30)
          .join('\n')
          .trim();
        if (archLines.length > 0) {
          architectureSummary = archLines;
        }
      }
    } catch {
      // ARCHITECTURE.md yoksa atla
    }

    // ---- Aşama görevlerini madde halinde listele ----
    const phaseLines: string[] = [];
    for (const phase of phases) {
      if (!phase.tasks || phase.tasks.length === 0) continue;
      phaseLines.push(`### Phase ${phase.order}: ${phase.name}`);
      phaseLines.push('');
      for (const task of phase.tasks) {
        const check = task.status === 'done' ? 'x' : ' ';
        phaseLines.push(`- [${check}] ${task.title}`);
      }
      phaseLines.push('');
    }

    // ---- Tarih ----
    const generatedAt = new Date().toISOString().split('T')[0];

    // ---- README.md içeriğini oluştur ----
    const readmeLines = [
      `# ${project.name}`,
      '',
      `> ${project.description || 'An AI Dev Studio project.'}`,
      '',
      '---',
      '',
      '## Tech Stack',
      '',
      ...techItems,
      '',
      '## Project Structure',
      '',
      '```',
      fileTree,
      '```',
      '',
      '## Getting Started',
      '',
      '### Prerequisites',
      '',
      '- Node.js 18+',
      '- pnpm (recommended) or npm',
      '',
      '### Installation',
      '',
      '```bash',
      'pnpm install',
      '```',
      '',
      '### Running',
      '',
      '```bash',
      '# Development',
      'pnpm dev',
      '',
      '# Build',
      'pnpm build',
      '',
      '# Tests',
      'pnpm test',
      '```',
      '',
      '## Project Plan',
      '',
      `- **Total Tasks:** ${totalTasks} (${doneTasks} completed)`,
      `- **Phases:** ${phases.length}`,
      '',
      ...phaseLines,
      '## Team',
      '',
      `Built by AI Dev Studio with ${agentCount} AI agent${agentCount !== 1 ? 's' : ''}:`,
      '',
      ...teamLines,
      '',
    ];

    // Architecture bölümü yalnızca içerik varsa ekle
    if (architectureSummary) {
      readmeLines.push(
        '## Architecture',
        '',
        architectureSummary,
        '',
      );
    }

    readmeLines.push(
      '---',
      '',
      `*Generated by [AI Dev Studio](https://github.com/voltagent/voltagent) on ${generatedAt}.*`,
      '',
    );

    // ---- README.md dosyasını repo köküne yaz ----
    const readmePath = join(project.repoPath, 'README.md');
    await writeFile(readmePath, readmeLines.join('\n'), 'utf-8');
    log?.('[readme] README.md oluşturuldu');

    // ---- Git'e commit et ----
    try {
      await gitManager.commitFiles(project.repoPath, ['README.md'], 'docs: auto-generate README.md');
      log?.('[readme] README.md git commit edildi');
    } catch {
      // Commit başarısız olsa da dosya yazıldı — loglayıp devam et
      log?.('[readme] README.md yazıldı (git commit başarısız)');
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log?.(`[readme] Hata: ${msg.slice(0, 200)}`);
  }
}

/** İlk harfi büyük yapar */
function capitalize(str: string): string {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ---------------------------------------------------------------------------
// Docs freshness check
// ---------------------------------------------------------------------------

export interface DocFreshnessResult {
  file: string;
  status: 'filled' | 'tbd' | 'missing';
}

/** Check which docs are still TBD or missing. */
export async function checkDocsFreshness(repoPath: string): Promise<DocFreshnessResult[]> {
  const docsDir = join(repoPath, 'docs');
  const docFiles = ['PROJECT.md', 'ARCHITECTURE.md', 'CODING_STANDARDS.md', 'API_CONTRACT.md', 'CHANGELOG.md', 'DECISIONS.md'];
  const results: DocFreshnessResult[] = [];

  for (const file of docFiles) {
    const filePath = join(docsDir, file);
    if (!existsSync(filePath)) {
      results.push({ file, status: 'missing' });
      continue;
    }
    try {
      const content = await readFile(filePath, 'utf-8');
      const isTBD = content.includes('TBD') && content.trim().length < 100;
      results.push({ file, status: isTBD ? 'tbd' : 'filled' });
    } catch {
      results.push({ file, status: 'missing' });
    }
  }

  return results;
}
