/**
 * Auto-documentation generator for AI Dev Studio projects.
 *
 * Updates project docs (PROJECT.md, ARCHITECTURE.md, API_CONTRACT.md, CHANGELOG.md)
 * based on agent role and task completion — no extra AI token cost.
 */

import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { gitManager } from './git-manager.js';
import { getLatestPlan, listPhases } from './db.js';
import type { Project, Task, AgentConfig, Phase } from './types.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Called after a task completes. Based on agent role, updates relevant docs.
 * Non-blocking — errors are caught and logged.
 */
export async function updateDocsAfterTask(
  project: Project,
  task: Task,
  agent: AgentConfig,
  log?: (msg: string) => void,
): Promise<void> {
  if (!project.repoPath) return;
  const docsDir = join(project.repoPath, 'docs');
  if (!existsSync(docsDir)) return;

  try {
    switch (agent.role) {
      case 'pm':
        await generateProjectMd(project, docsDir, log);
        break;
      case 'architect':
        await generateArchitectureMd(project, docsDir, log);
        break;
      case 'backend':
        await generateApiContractMd(project, task, docsDir, log);
        break;
      case 'reviewer':
        await generateCodingStandardsMd(project, docsDir, log);
        break;
    }

    // Always append to CHANGELOG after any completed task
    await appendChangelog(project, task, agent, docsDir, log);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log?.(`[docs] Hata: ${msg.slice(0, 200)}`);
  }
}

// ---------------------------------------------------------------------------
// PROJECT.md — PM Agent
// ---------------------------------------------------------------------------

async function generateProjectMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const plan = getLatestPlan(project.id);
  if (!plan) return;

  const phases = listPhases(plan.id);
  const techStack = project.techStack.length > 0 ? project.techStack.join(', ') : 'Not specified';

  const lines = [
    '# Project',
    '',
    '> Generated by AI Dev Studio PM Agent.',
    '',
    '## Overview',
    '',
    project.description || 'No description provided.',
    '',
    '## Tech Stack',
    '',
    techStack,
    '',
    '## Requirements',
    '',
    ...phases.flatMap((phase) =>
      phase.tasks.map((t) => `- ${t.title}${t.description ? `: ${t.description.slice(0, 120)}` : ''}`),
    ),
    '',
    '## Project Plan',
    '',
    `- **Version:** ${plan.version}`,
    `- **Phases:** ${phases.length}`,
    `- **Total Tasks:** ${phases.reduce((sum, p) => sum + p.tasks.length, 0)}`,
    '',
    ...phases.map(
      (p) =>
        `### Phase ${p.order}: ${p.name}\n${p.tasks.map((t) => `- [${t.status === 'done' ? 'x' : ' '}] ${t.title} (${t.assignedAgent})`).join('\n')}`,
    ),
    '',
  ];

  await writeFile(join(docsDir, 'PROJECT.md'), lines.join('\n'), 'utf-8');
  log?.('[docs] PROJECT.md guncellendi');
}

// ---------------------------------------------------------------------------
// ARCHITECTURE.md — Architect Agent
// ---------------------------------------------------------------------------

interface TreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: TreeNode[];
}

function renderTree(nodes: TreeNode[], prefix = ''): string[] {
  const lines: string[] = [];
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];
    const isLast = i === nodes.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    lines.push(`${prefix}${connector}${node.name}`);
    if (node.children && node.children.length > 0) {
      const childPrefix = prefix + (isLast ? '    ' : '│   ');
      lines.push(...renderTree(node.children, childPrefix));
    }
  }
  return lines;
}

async function generateArchitectureMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const techStack = project.techStack.length > 0 ? project.techStack.join(', ') : 'Not specified';

  let fileTree = '';
  try {
    const tree = await gitManager.getFileTree(project.repoPath);
    const treeLines = renderTree(tree);
    fileTree = treeLines.slice(0, 60).join('\n'); // limit to 60 lines
    if (treeLines.length > 60) fileTree += '\n... (truncated)';
  } catch {
    fileTree = 'Unable to read file tree.';
  }

  const lines = [
    '# Architecture',
    '',
    '> Generated by AI Dev Studio Architect Agent.',
    '',
    '## Tech Stack',
    '',
    techStack,
    '',
    '## Project Structure',
    '',
    '```',
    fileTree,
    '```',
    '',
    '## Components',
    '',
    'See individual source files for component documentation.',
    '',
  ];

  await writeFile(join(docsDir, 'ARCHITECTURE.md'), lines.join('\n'), 'utf-8');
  log?.('[docs] ARCHITECTURE.md guncellendi');
}

// ---------------------------------------------------------------------------
// API_CONTRACT.md — Backend Agent
// ---------------------------------------------------------------------------

async function generateApiContractMd(
  project: Project,
  task: Task,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  // Only update if task is API-related
  const apiKeywords = ['api', 'route', 'endpoint', 'rest', 'controller', 'handler'];
  const isApiTask =
    apiKeywords.some((kw) => task.title.toLowerCase().includes(kw)) ||
    apiKeywords.some((kw) => task.description.toLowerCase().includes(kw));

  if (!isApiTask) return;

  const existingPath = join(docsDir, 'API_CONTRACT.md');
  let existing = '';
  try {
    existing = await readFile(existingPath, 'utf-8');
  } catch { /* ignore */ }

  // If doc already has real content (not just TBD), append rather than overwrite
  const isTBD = existing.includes('TBD') && existing.length < 50;

  const filesCreated = task.output?.filesCreated ?? [];
  const filesModified = task.output?.filesModified ?? [];
  const allFiles = [...filesCreated, ...filesModified];
  const routeFiles = allFiles.filter(
    (f) => f.includes('route') || f.includes('controller') || f.includes('api') || f.includes('handler'),
  );

  if (routeFiles.length === 0 && isTBD) return;

  const taskEntry = [
    '',
    `## ${task.title}`,
    '',
    `> Task ID: ${task.id}`,
    `> Completed: ${task.completedAt || new Date().toISOString()}`,
    '',
    routeFiles.length > 0
      ? `**Route files:** ${routeFiles.join(', ')}`
      : `**Related files:** ${allFiles.slice(0, 5).join(', ')}`,
    '',
    task.description.slice(0, 500),
    '',
  ].join('\n');

  if (isTBD) {
    const lines = [
      '# API Contract',
      '',
      '> Generated by AI Dev Studio Backend Agent.',
      taskEntry,
    ];
    await writeFile(existingPath, lines.join('\n'), 'utf-8');
  } else {
    await writeFile(existingPath, existing + '\n' + taskEntry, 'utf-8');
  }

  log?.('[docs] API_CONTRACT.md guncellendi');
}

// ---------------------------------------------------------------------------
// CODING_STANDARDS.md — Reviewer Agent
// ---------------------------------------------------------------------------

async function generateCodingStandardsMd(
  project: Project,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const existingPath = join(docsDir, 'CODING_STANDARDS.md');
  let existing = '';
  try {
    existing = await readFile(existingPath, 'utf-8');
  } catch { /* ignore */ }

  // Only fill if still TBD
  if (!existing.includes('TBD')) return;

  const techStack = project.techStack.join(', ') || 'TypeScript';

  const lines = [
    '# Coding Standards',
    '',
    '> Generated by AI Dev Studio Reviewer Agent.',
    '',
    `## Tech Stack: ${techStack}`,
    '',
    '## Formatting',
    '',
    '- ESLint + Prettier enforced automatically after each task',
    '- Single quotes, semicolons, trailing commas',
    '- Max line width: 100 characters',
    '- 2-space indentation',
    '',
    '## Naming Conventions',
    '',
    '- **Files:** kebab-case (e.g., `user-service.ts`)',
    '- **Classes/Interfaces:** PascalCase',
    '- **Functions/Variables:** camelCase',
    '- **Constants:** UPPER_SNAKE_CASE',
    '',
    '## Best Practices',
    '',
    '- Use TypeScript strict mode',
    '- Prefer `const` over `let`',
    '- Avoid `any` — use proper types',
    '- Write unit tests for business logic',
    '- Keep functions small and focused',
    '',
  ];

  await writeFile(existingPath, lines.join('\n'), 'utf-8');
  log?.('[docs] CODING_STANDARDS.md guncellendi');
}

// ---------------------------------------------------------------------------
// CHANGELOG.md — All agents (append after each task)
// ---------------------------------------------------------------------------

async function appendChangelog(
  project: Project,
  task: Task,
  agent: AgentConfig,
  docsDir: string,
  log?: (msg: string) => void,
): Promise<void> {
  const changelogPath = join(docsDir, 'CHANGELOG.md');
  let existing = '';
  try {
    existing = await readFile(changelogPath, 'utf-8');
  } catch { /* ignore */ }

  const date = new Date().toISOString().split('T')[0];
  const filesCount =
    (task.output?.filesCreated?.length ?? 0) + (task.output?.filesModified?.length ?? 0);

  const entry = `\n- **${date}** — ${task.title} (${agent.name}, ${agent.role}) — ${filesCount} files\n`;

  // Avoid duplicate entries for the same task
  if (existing.includes(task.id)) return;

  // Insert after header line
  const headerEnd = existing.indexOf('\n\n');
  if (headerEnd > -1) {
    const before = existing.slice(0, headerEnd + 2);
    const after = existing.slice(headerEnd + 2);
    await writeFile(changelogPath, before + entry + after, 'utf-8');
  } else {
    await writeFile(changelogPath, existing + entry, 'utf-8');
  }

  log?.('[docs] CHANGELOG.md guncellendi');
}

// ---------------------------------------------------------------------------
// Docs freshness check
// ---------------------------------------------------------------------------

export interface DocFreshnessResult {
  file: string;
  status: 'filled' | 'tbd' | 'missing';
}

/** Check which docs are still TBD or missing. */
export async function checkDocsFreshness(repoPath: string): Promise<DocFreshnessResult[]> {
  const docsDir = join(repoPath, 'docs');
  const docFiles = ['PROJECT.md', 'ARCHITECTURE.md', 'CODING_STANDARDS.md', 'API_CONTRACT.md', 'CHANGELOG.md', 'DECISIONS.md'];
  const results: DocFreshnessResult[] = [];

  for (const file of docFiles) {
    const filePath = join(docsDir, file);
    if (!existsSync(filePath)) {
      results.push({ file, status: 'missing' });
      continue;
    }
    try {
      const content = await readFile(filePath, 'utf-8');
      const isTBD = content.includes('TBD') && content.trim().length < 100;
      results.push({ file, status: isTBD ? 'tbd' : 'filled' });
    } catch {
      results.push({ file, status: 'missing' });
    }
  }

  return results;
}
